### ISSUE TITLE
Support for Honeywell T series Thermostats 

### ISSUE THREAD

**Issue by donavanbecker** [Tommrodrigues/homebridge-web-thermostat#1]
Anyway that this could support one of these thermostats since it’s web based?

**Comment by phenotypic** [comment]
Unfortunately, in its current form, this plugin is not design to work with the thermostats you have listed. Of course, you are welcome to fork the repository and make changes so that those thermostats are supported. 

However, a quick search for 'homebridge honeywell'  returns a number of plugins that may be better suited to your needs (e.g. [homebridge-tcc](https://github.com/NorthernMan54/homebridge-tcc))
