### ISSUE TITLE
Cooling Only Mode

### ISSUE THREAD

**Issue by AxelSariel** [Tommrodrigues/homebridge-web-thermostat#15]
Hi! I'v been working to add this plugin to my Homebridge setup, and I noticed that it had the heatOnly, but I needed the coolOnly feature instead. 

Since Cooling (2) and Auto (3) are after Heat (1), maxValue would not work in this case. I investigated some on how it works, and found it could also be done with validValues instead of maxValue.

I adapted the plugin in my setup with validValues and it works well, I include the relevant piece of code below for consideration. Maybe the config could be adapted to set separate modes as true or false.

```
if (this.coolOnly) {
      this.service.getCharacteristic(Characteristic.TargetHeatingCoolingState)
        .setProps({
          validValues: [0, 2, 3]
        })
      this.log('Set to cool only')
    }
```

Thanks!

**Comment by phenotypic** [comment]
Hi there, I'm pleased to hear you've been playing around with the plug-in. 

It's handy to know that `validValues` will work instead. I think it's a good idea as you suggested to allow for `coolOnly` as well as `heatOnly`. 

I'll look to implement that feature in the near future. I think the best approach would simply be defining the `validValues` array in the `config.json`, rather than including multiple if statements, but I'll have a little play around at some point and see what works best.

**Comment by phenotypic** [comment]
Hi there, your suggestion has been integrated in the latest release of this plugin. For cool only mode, simply set `validStates` to `[0, 2, 3]` in the `config.json`

**Comment by AxelSariel** [comment]
Nice to know, thanks for integrating it!
