### ISSUE TITLE
Error setting targetHeatingCoolingState: socket hang up

### ISSUE THREAD

**Issue by Kompass02** [Tommrodrigues/homebridge-web-thermostat#16]
Hi, I'm getting this error in the homebridge log file:

```
Error setting targetHeatingCoolingState: socket hang up
```

But my ESP8266 successfully sets the HeatingCoolingState.

Here is my current ESP8266 request handler:

```cpp
server.on("/targetHeatingCoolingState", handle_targetHeatingCoolingState);

void handle_targetHeatingCoolingState () {
  String value = server.arg("value");
  tarState = value.toInt();

  Serial.print("\n tarState: ");
  Serial.println(tarState);
}
```

Thanks in advance!

**Comment by phenotypic** [comment]
Hi there, I believe you are having this issue because you are not returning an `HTTP 200 OK` status response back after receiving a request .

See line `157` of [this](https://github.com/Tommrodrigues/homebridge-web-boiler/blob/master/examples/NodeMCU-Boiler.ino) script to see how to properly handle requests.

You might want to change your code to something like this:

```cpp
server.on("/targetHeatingCoolingState", handle_targetHeatingCoolingState);

void handle_targetHeatingCoolingState () {
  tarState = server.arg("value").toInt();
  server.send(200);
  Serial.print("\n tarState: " + String(tarState));
}
```
