### ISSUE TITLE
Need example please

### ISSUE THREAD

**Issue by GevaudanBeast** [Tommrodrigues/homebridge-web-thermostat#23]
Hello,
Can you give some example for the config.json
I want to use with a restfull API work like this :
CONSIGN URL :
URL : `http://xxx.xxx.xxx.xxx/api/object/thermostat/1638403?ApiKey=xxxxx`
Method : `GET`
Body : `{  "anaCurrSetPoint": 21  }`
Thx for your work

**Comment by phenotypic** [comment]
Hi there, you can see an example of the `config.json` in the [Configuration](https://github.com/phenotypic/homebridge-web-thermostat#configuration) section of the `README`.

You should also refer to the [API Interfacing](https://github.com/phenotypic/homebridge-web-thermostat#api-interfacing) section to see what is expected of your API. It seems like the response from your API does not meet these requirements and so will not work with this plugin.

Please feel free to fork this plugin and adapt it in order to work with your device.
