### ISSUE TITLE
error timeout

### ISSUE THREAD

**Issue by QDUNI** [Tommrodrigues/homebridge-web-thermostat#6]
Hi,

Im getting this error when connecting to my api.
Error setting targetHeatingCoolingState: ESOCKETTIMEDOUT
 if I type in the url from the browser it works.
any ideas?

**Comment by phenotypic** [comment]
There are a couple of things that could cause this problem. 

You should ensure that your API returns a `200` HTTP response code when it receives a request - see [here](https://github.com/Tommrodrigues/homebridge-web-boiler/blob/master/examples/NodeMCU-Boiler.ino) for an example of a script which handles requests correctly. 

Otherwise, the problem will most likely be a connection issue between the two devices.

**Comment by Tapsel99** [comment]
I have the same problem, sometimes it works and than it will again completely stop working and say timeout, device is not responding in home app.
Any idea?
[Thermostat] Error getting status: ESOCKETTIMEDOUT
[Thermostat] Error setting targetTemperature: ESOCKETTIMEDOUT

**Comment by phenotypic** [comment]
@Tapsel99 Please refer to your issue #21.
